### ISSUE TITLE
New layouts for BGC projections Figure

### ISSUE THREAD

**Issue by cmahony** [whmacken/2019_CCISS#5]
@whmacken, Following up on our Feb 10th discussion, i reworked the layout of Figure 2 and made an alternative figure with a simpler layout. 

Here is the reworked complex layout (i changed the positions of the recent period and exotic units maps):
![CCISS manu BGCprojections 2025](https://user-images.githubusercontent.com/17104005/79161720-d32e2200-7d90-11ea-84bf-3134e3733e9f.png)

Here is the alternative (simpler) layout:
![CCISS manu BGCprojections ALT 2025](https://user-images.githubusercontent.com/17104005/79161784-eccf6980-7d90-11ea-93a6-77679f454979.png)

**Comment by whmacken** [comment]
Looks great - this layout is cleaner/clearer. Label the "BGC unit" as "BGC subzone/variant" I think to avoid any confusion. And the black triangles may need to be labelled as well. And add the location of exotic zones in (?)

**Comment by cmahony** [comment]
which one do you prefer, the complex or the simple?

**Comment by whmacken** [comment]
Sorry. Simple.

**Comment by whmacken** [comment]
But, should there be a map that matches the 2080 model circled in the graph?

**Comment by cmahony** [comment]
i'll likely take that out.

**Comment by whmacken** [comment]
Check and Roger.
